name: Scrape details

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'
          cache: false

      - name: Install pup HTML parser
        run: |
          go install github.com/ericchiang/pup@latest
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Install GNU parallel
        run: |
          sudo apt-get update
          sudo apt-get install -y parallel

      - name: Make scripts executable
        run: chmod +x ./scrape-details.sh

      - name: Run the scrapers
        run: |
          ./scrape-details.sh

      - name: Commit and push changes
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update scraped data: ${timestamp}" || exit 0
          git pull --rebase
          git push
